# Gauss Elimination Method

In [1]:
from datetime import datetime as dt
import numpy as np
from numpy import Infinity
# r=int(input("no of rows"))
# c=int(input("no of columns"))
# m=[]
# for H in range(r):
#     l=[]
#     for K in range(c):
#         u=float(input("enter the element rowise"))
#         l.append(u)
#         print(l)
#     m.append(l)
#     a=np.array(m)
# print(a)
# q=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element b"))
#         l.append(u)
#     q.append(l)
#     b=np.array(q,dtype=np.float64)
# print(b)

a=np.array([[2,1,1],[1,3,-1],[-1,1,2]],dtype=np.float64)
b=np.array([[6],[0],[3]],dtype=np.float64)
itime=dt.now()
r=3
c=3
# #Diagonal Dominant
# def DD(A): 
#     for i in range(0,len(A)):
#         sum = 0 
#         for j in range(0,len(A)):
#                 sum = sum+abs(A[i][j])
#         sum = sum - abs(A[i][i])
#         # print(sum)

#         if abs(A[i][i])<=sum:
#             return False
#     return True
    
red=np.empty([r,c+1])
mat=np.concatenate((a,b),axis=1,dtype=np.float64)
print(mat)
sol=np.empty([len(mat),1])
m=0
while m<r:
    for i in range(m,r):
        L=mat[i][m]
        for j in range(m,c+1):
            red[i][j]=mat[i][j]/L
    for k in range(m+1,r):
        for l in range(m,c+1):
            red[k][l]=red[k][l]-red[m][l]
            mat=red
    m=m+1
# BACK SUBSTITUTION 
m=len(mat)-1
n=len(mat[0])-1
sol[m]=mat[m][n]
if sol[m]==Infinity:
    print("solution does't exist")
else:
    for i in range(m,-1,-1):
        sol[i] = mat[i][n]
        for j in range(i+1,n):
            sol[i] = sol[i]-mat[i][j]*sol[j]
    print("sol",sol)
ftime=dt.now()
print("The cost of computation is ",ftime-itime)




[[ 2.  1.  1.  6.]
 [ 1.  3. -1.  0.]
 [-1.  1.  2.  3.]]
sol [[1.76470588]
 [0.17647059]
 [2.29411765]]
The cost of computation is  0:00:00.001143


# Gauss Jacobi method

In [2]:
from datetime import datetime as dt
import numpy as np
# r=int(input("no of rows"))
# c=int(input("no of columns"))
# m=[]
# for H in range(r):
#     l=[]
#     for K in range(c):
#         u=float(input("enter the element of a rowise "))
#         l.append(u)
#     m.append(l)
#     a=np.array(m,dtype=np.float64)
# q=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element of b"))
#         l.append(u)
#     q.append(l)
#     b=np.array(q,dtype=np.float64)
# pivoting
a=[[2,1,1],[1,3,-1],[-1,1,2]]
b=[6,0,3]
# o=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element of initial vector "))
#         l.append(u)
#     o.append(l)
#     x0=np.array(o,dtype=np.float64)
x0=[0,1,1]
e=0.0001
r=3
itime=dt.now()
ltm=np.zeros([r,r])
utm=np.zeros([r,r])
dm=np.zeros([r,r])
for i in range(0,r):
    for j in range(0,r):
        if i>j:
            ltm[i][j]=a[i][j]
        elif i<j:
            utm[i][j]=a[i][j]
        else:
            dm[i][i]=a[i][i]
dm_in=np.linalg.inv(dm)
h=-np.dot(dm_in,(ltm+utm))
C=np.dot(dm_in,b)
k=1
i=0
while k>=e :
    x1=np.dot(h,x0)+C
    x=abs(x0-x1)
    k=x.max()
    '''for g in range(len(x0)):
        x.append(abs(x0[g,0]-x1[g,0]))  
        k=max(x)
        # print("k",k)
        '''
    x0=x1
    i=i+1
print("solution",x0)
ftime=dt.now()
print("The cost of computation is ",ftime-itime)


solution [1.76474173 0.17643859 2.29419286]
The cost of computation is  0:00:00.003993


# Gauss Seidal method

In [4]:
from datetime import datetime as dt
import numpy as np
# r=int(input("no of rows"))
# c=int(input("no of columns"))
# m=[]
# for H in range(r):
#     l=[]
#     for K in range(c):
#         u=float(input("enter the element of a rowise "))
#         l.append(u)
#     m.append(l)
#     a=np.array(m,dtype=np.float64)
# q=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element of b"))
#         l.append(u)
#     q.append(l)
#     b=np.array(q,dtype=np.float64)
# o=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element of initial vector "))
#         l.append(u)
#     o.append(l)
#     x0=np.array(o,dtype=np.float64)
# e=float(input("enter tolerence "))

a=[[2,1,1],[1,3,-1],[-1,1,2]]
b=[6,0,3]
x0=[0,1,1]
e=0.0001
itime=dt.now()
# pivoting
r=3
ltm=np.zeros([r,r])
utm=np.zeros([r,r])
dm=np.zeros([r,r])
for i in range(0,r):
    for j in range(0,r):
        if i>j:
            ltm[i][j]=a[i][j]
        elif i<j:
            utm[i][j]=a[i][j]
        else:
            dm[i][i]=a[i][i]
inv=np.linalg.inv(ltm+dm)
h=-np.dot(inv,(utm))
C=np.dot(inv,b)

k=1
i=0
while k>=e :
    x1=np.dot(h,x0)+C
    x=abs(x0-x1)
    k=x.max()
    x0=x1
    i=i+1
print("solution",x0)
ftime=dt.now()
print("The cost of computation is ",ftime-itime)


solution [1.76468669 0.17646216 2.29411227]
The cost of computation is  0:00:00.001850
