# Gauss Elimination Method

In [1]:
from datetime import datetime as dt
import numpy as np
from numpy import Infinity
# r=int(input("no of rows"))
# c=int(input("no of columns"))
# m=[]
# for H in range(r):
#     l=[]
#     for K in range(c):
#         u=float(input("enter the element rowise"))
#         l.append(u)
#         print(l)
#     m.append(l)
#     a=np.array(m)
# print(a)
# q=[]
# for H in range(r):
#     l=[]
#     for K in range(1):
#         u=float(input("enter the element b"))
#         l.append(u)
#     q.append(l)
#     b=np.array(q,dtype=np.float64)
# print(b)

a=np.array([[2,1,1],[1,3,-1],[-1,1,2]],dtype=np.float64)
b=np.array([[6],[0],[3]],dtype=np.float64)
itime=dt.now()
r=3
c=3
# #Diagonal Dominant
# def DD(A): 
#     for i in range(0,len(A)):
#         sum = 0 
#         for j in range(0,len(A)):
#                 sum = sum+abs(A[i][j])
#         sum = sum - abs(A[i][i])
#         # print(sum)

#         if abs(A[i][i])<=sum:
#             return False
#     return True
    
red=np.empty([r,c+1])
mat=np.concatenate((a,b),axis=1,dtype=np.float64)
print(mat)
sol=np.empty([len(mat),1])
m=0
while m<r:
    for i in range(m,r):
        L=mat[i][m]
        for j in range(m,c+1):
            red[i][j]=mat[i][j]/L
    for k in range(m+1,r):
        for l in range(m,c+1):
            red[k][l]=red[k][l]-red[m][l]
            mat=red
    m=m+1
# BACK SUBSTITUTION 
m=len(mat)-1
n=len(mat[0])-1
sol[m]=mat[m][n]
if sol[m]==Infinity:
    print("solution does't exist")
else:
    for i in range(m,-1,-1):
        sol[i] = mat[i][n]
        for j in range(i+1,n):
            sol[i] = sol[i]-mat[i][j]*sol[j]
    print("sol",sol)
ftime=dt.now()
print("The cost of computation is ",ftime-itime)




[[ 2.  1.  1.  6.]
 [ 1.  3. -1.  0.]
 [-1.  1.  2.  3.]]
sol [[1.76470588]
 [0.17647059]
 [2.29411765]]
The cost of computation is  0:00:00.001143
